name: Images in GitHub
on: [push]

jobs:
  build-and-push:
    name: Build and push all images
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      #- uses: docker://docker.io/cilium/image-maker:3e2ea4f151593908c362307a1de22e68610d955c
      #  name: Register binfmt from multi-platform builds
      #  with:
      #    entrypoint: docker
      #    args: run --privileged linuxkit/binfmt:5d33e7346e79f9c13a73c6952669e47a53b063d4
      #- uses: docker://docker.io/cilium/image-maker:3e2ea4f151593908c362307a1de22e68610d955c
      #  name: Run make iproute2-image
      #  env:
      #    DOCKER_HUB_PUBLIC_ACCESS_ONLY: true
      #    ANY_REGISTRY_USERNAME: errordeveloper
      #    ANY_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    entrypoint: make
      #    args: iproute2-image PUSH=true REGISTRIES=docker.pkg.github.com/errordeveloper/cilium-image-tools
